load("@rules_qt//:qt.bzl", "qt_cc_binary", "qt_cc_library")

qt_cc_library(
    name = "duolingo_lib",
    srcs = glob(["src/*.cpp"]),
    hdrs = glob(["src/*.h"]),
    data = glob(["data/*"]),
    deps = [
        "@rules_qt//:qt_core",
        "@rules_qt//:qt_gui",
        "@rules_qt//:qt_multimedia",
        "@rules_qt//:qt_sql",
        "@rules_qt//:qt_widgets",
    ],
)

qt_cc_binary(
    name = "duolingo",
    srcs = ["src/main.cpp"],
    deps = [":duolingo_lib"],
)
