load("@rules_qt//:qt.bzl", "qt_cc_binary", "qt_cc_library")

qt_cc_library(
    name = "duolingo_lib",
    srcs = glob(["src/*.cpp"]),
    hdrs = glob(["src/*.h"]),
    deps = [
        "@rules_qt//:qt_core",
        "@rules_qt//:qt_gui",
        "@rules_qt//:qt_widgets",
    ],
)

qt_cc_binary(
    name = "duolingo",
    srcs = glob(["main.cpp"]),
    data = glob(["data/**"]),
    deps = [":duolingo_lib"],
)
