#ifndef DATABASE_H
#define DATABASE_H

#include "ExerciseTypes.h"
#include "TaskDifficulty.h"

#include <QString>
#include <memory>
#include <vector>

namespace DataBase {

const int kQuestions = 30;

struct GrammarTask {
    std::unique_ptr<QString> question{};
    std::unique_ptr<std::vector<QString>> options{};
    std::unique_ptr<int> answer{};
};

struct TranslationTask {
    std::unique_ptr<QString> question{};
    std::unique_ptr<QString> answer{};
};

inline const std::vector<std::vector<QString>> grammar_questions = {
  {
    QString("She ___ a cat."),
    QString("My brother ___ in London last year."),
    QString("I ___ English lessons every Monday."),
    QString("I ___ to school every day."),
    QString("My brother ___ in London last year."),
    QString("I ___ English lessons every Monday."),
    QString("She ___ TV at the moment."),
    QString("We ___ breakfast at 7 a.m. yesterday."),
    QString("My brother ___ in London last year."),
    QString("We ___ breakfast at 7 a.m. yesterday."),
    QString("She ___ TV at the moment."),
    QString("I ___ English lessons every Monday."),
    QString("I ___ English lessons every Monday."),
    QString("She ___ TV at the moment."),
    QString("I ___ to school every day."),
    QString("My brother ___ in London last year."),
    QString("There ___ two books on the table."),
    QString("He ___ here right now."),
    QString("She ___ a cat."),
    QString("They ___ basketball now."),
    QString("I ___ English lessons every Monday."),
    QString("I ___ to school every day."),
    QString("We ___ breakfast at 7 a.m. yesterday."),
    QString("She ___ TV at the moment."),
    QString("We ___ breakfast at 7 a.m. yesterday."),
    QString("They ___ basketball now."),
    QString("She ___ TV at the moment."),
    QString("He ___ here right now."),
    QString("She ___ a cat."),
    QString("They ___ basketball now."),
  },
  {
    QString("This is the most interesting book ___ I’ve ever read."),
    QString("I’d rather you ___ smoking in here."),
    QString("They ___ dinner when I arrived."),
    QString("They ___ dinner when I arrived."),
    QString("There isn’t ___ milk left."),
    QString("I’d rather you ___ smoking in here."),
    QString("I haven’t seen him ___ Monday."),
    QString("He ___ to Paris last summer."),
    QString("There isn’t ___ milk left."),
    QString("I haven’t seen him ___ Monday."),
    QString("By this time tomorrow, we ___ the test."),
    QString("They ___ dinner when I arrived."),
    QString("I’d rather you ___ smoking in here."),
    QString("She’s better ___ chess than I am."),
    QString("This is the most interesting book ___ I’ve ever read."),
    QString("They ___ dinner when I arrived."),
    QString("If I ___ rich, I would travel the world."),
    QString("By this time tomorrow, we ___ the test."),
    QString("I ___ here since 2019."),
    QString("If I ___ rich, I would travel the world."),
    QString("I haven’t seen him ___ Monday."),
    QString("By this time tomorrow, we ___ the test."),
    QString("This is the most interesting book ___ I’ve ever read."),
    QString("This is the most interesting book ___ I’ve ever read."),
    QString("There isn’t ___ milk left."),
    QString("I ___ here since 2019."),
    QString("They ___ dinner when I arrived."),
    QString("I’d rather you ___ smoking in here."),
    QString("He ___ to Paris last summer."),
    QString("They ___ dinner when I arrived."),
  },
  {
    QString("If she ___ earlier, she would have caught the train."),
    QString("Not only ___ to the manager, but he also sent an email."),
    QString("Hardly ___ when the phone rang."),
    QString("He acts as if he ___ everything."),
    QString("It’s high time you ___ to bed."),
    QString("Not only ___ to the manager, but he also sent an email."),
    QString("If she ___ earlier, she would have caught the train."),
    QString("If she ___ earlier, she would have caught the train."),
    QString("I wish I ___ French when I was younger."),
    QString("Not only ___ to the manager, but he also sent an email."),
    QString("Hardly ___ when the phone rang."),
    QString("Rarely ___ such a beautiful performance."),
    QString("He acts as if he ___ everything."),
    QString("By the time you arrive, they ___ dinner."),
    QString("Not only ___ to the manager, but he also sent an email."),
    QString("The project ___ by the team before the deadline next week."),
    QString("The project ___ by the team before the deadline next week."),
    QString("Not only ___ to the manager, but he also sent an email."),
    QString("By the time you arrive, they ___ dinner."),
    QString("I wish I ___ French when I was younger."),
    QString("I wish I ___ French when I was younger."),
    QString("Not only ___ to the manager, but he also sent an email."),
    QString("I wish I ___ French when I was younger."),
    QString("Rarely ___ such a beautiful performance."),
    QString("Hardly ___ when the phone rang."),
    QString("She suggested ___ earlier to avoid traffic."),
    QString("She suggested ___ earlier to avoid traffic."),
    QString("Not only ___ to the manager, but he also sent an email."),
    QString("I wish I ___ French when I was younger."),
    QString("The project ___ by the team before the deadline next week."),
  }};

inline const std::vector<std::vector<std::vector<QString>>> grammar_options = {
  {
    {QString("having"), QString("has"), QString("had"), QString("have")},
    {QString("living"), QString("lived"), QString("lives"), QString("live")},
    {QString("having"), QString("has"), QString("had"), QString("have")},
    {QString("goes"), QString("going"), QString("gone"), QString("go")},
    {QString("live"), QString("living"), QString("lived"), QString("lives")},
    {QString("had"), QString("has"), QString("have"), QString("having")},
    {QString("is watching"), QString("watching"), QString("watches"), QString("watch")},
    {QString("eating"), QString("eat"), QString("ate"), QString("eaten")},
    {QString("live"), QString("living"), QString("lives"), QString("lived")},
    {QString("eating"), QString("eaten"), QString("ate"), QString("eat")},
    {QString("watching"), QString("is watching"), QString("watches"), QString("watch")},
    {QString("had"), QString("having"), QString("has"), QString("have")},
    {QString("have"), QString("has"), QString("having"), QString("had")},
    {QString("watching"), QString("watches"), QString("watch"), QString("is watching")},
    {QString("going"), QString("go"), QString("gone"), QString("goes")},
    {QString("living"), QString("lived"), QString("live"), QString("lives")},
    {QString("be"), QString("are"), QString("is"), QString("am")},
    {QString("is"), QString("be"), QString("am"), QString("are")},
    {QString("having"), QString("have"), QString("had"), QString("has")},
    {QString("play"), QString("are playing"), QString("plays"), QString("playing")},
    {QString("have"), QString("having"), QString("had"), QString("has")},
    {QString("going"), QString("gone"), QString("go"), QString("goes")},
    {QString("ate"), QString("eating"), QString("eat"), QString("eaten")},
    {QString("watching"), QString("is watching"), QString("watches"), QString("watch")},
    {QString("eaten"), QString("ate"), QString("eat"), QString("eating")},
    {QString("play"), QString("playing"), QString("are playing"), QString("plays")},
    {QString("watches"), QString("is watching"), QString("watch"), QString("watching")},
    {QString("am"), QString("be"), QString("is"), QString("are")},
    {QString("has"), QString("had"), QString("having"), QString("have")},
    {QString("plays"), QString("play"), QString("are playing"), QString("playing")},
  },
  {
    {QString("who"), QString("whom"), QString("which"), QString("whose")},
    {QString("didn’t"), QString("don’t"), QString("won’t"), QString("not")},
    {QString("have"), QString("were having"), QString("are having"), QString("had")},
    {QString("are having"), QString("have"), QString("were having"), QString("had")},
    {QString("a few"), QString("much"), QString("few"), QString("many")},
    {QString("won’t"), QString("don’t"), QString("not"), QString("didn’t")},
    {QString("from"), QString("by"), QString("since"), QString("for")},
    {QString("went"), QString("was"), QString("had been"), QString("has been")},
    {QString("few"), QString("much"), QString("a few"), QString("many")},
    {QString("by"), QString("from"), QString("since"), QString("for")},
    {QString("finish"), QString("will have finished"), QString("have finished"),
     QString("will finish")},
    {QString("had"), QString("are having"), QString("have"), QString("were having")},
    {QString("don’t"), QString("not"), QString("won’t"), QString("didn’t")},
    {QString("at"), QString("for"), QString("on"), QString("in")},
    {QString("who"), QString("whose"), QString("whom"), QString("which")},
    {QString("are having"), QString("had"), QString("have"), QString("were having")},
    {QString("were"), QString("will be"), QString("was"), QString("am")},
    {QString("have finished"), QString("finish"), QString("will finish"),
     QString("will have finished")},
    {QString("lived"), QString("am living"), QString("live"), QString("have lived")},
    {QString("were"), QString("will be"), QString("was"), QString("am")},
    {QString("for"), QString("from"), QString("since"), QString("by")},
    {QString("finish"), QString("will have finished"), QString("will finish"),
     QString("have finished")},
    {QString("whose"), QString("which"), QString("who"), QString("whom")},
    {QString("who"), QString("whose"), QString("whom"), QString("which")},
    {QString("much"), QString("a few"), QString("few"), QString("many")},
    {QString("live"), QString("have lived"), QString("am living"), QString("lived")},
    {QString("are having"), QString("had"), QString("have"), QString("were having")},
    {QString("not"), QString("didn’t"), QString("don’t"), QString("won’t")},
    {QString("went"), QString("has been"), QString("was"), QString("had been")},
    {QString("were having"), QString("have"), QString("had"), QString("are having")},
  },
  {
    {QString("had left"), QString("left"), QString("would leave"), QString("leaves")},
    {QString("he spoke"), QString("did he speak"), QString("spoke he"), QString("he did speak")},
    {QString("had I sat down"), QString("sat I down"), QString("I sat down"),
     QString("I had sat down")},
    {QString("will know"), QString("had known"), QString("knew"), QString("knows")},
    {QString("go"), QString("had gone"), QString("went"), QString("will go")},
    {QString("did he speak"), QString("he spoke"), QString("he did speak"), QString("spoke he")},
    {QString("would leave"), QString("had left"), QString("left"), QString("leaves")},
    {QString("would leave"), QString("had left"), QString("left"), QString("leaves")},
    {QString("would learn"), QString("had learned"), QString("learn"), QString("learned")},
    {QString("spoke he"), QString("he did speak"), QString("did he speak"), QString("he spoke")},
    {QString("had I sat down"), QString("sat I down"), QString("I sat down"),
     QString("I had sat down")},
    {QString("I have seen"), QString("I did see"), QString("did I see"), QString("have I seen")},
    {QString("will know"), QString("knows"), QString("knew"), QString("had known")},
    {QString("will be finishing"), QString("will finish"), QString("have finished"),
     QString("will have finished")},
    {QString("he spoke"), QString("he did speak"), QString("spoke he"), QString("did he speak")},
    {QString("would complete"), QString("is completing"), QString("will have been completed"),
     QString("will complete")},
    {QString("will complete"), QString("is completing"), QString("would complete"),
     QString("will have been completed")},
    {QString("spoke he"), QString("he did speak"), QString("he spoke"), QString("did he speak")},
    {QString("have finished"), QString("will have finished"), QString("will be finishing"),
     QString("will finish")},
    {QString("learned"), QString("learn"), QString("would learn"), QString("had learned")},
    {QString("learned"), QString("learn"), QString("would learn"), QString("had learned")},
    {QString("spoke he"), QString("he did speak"), QString("he spoke"), QString("did he speak")},
    {QString("learn"), QString("had learned"), QString("would learn"), QString("learned")},
    {QString("have I seen"), QString("I did see"), QString("did I see"), QString("I have seen")},
    {QString("I sat down"), QString("had I sat down"), QString("I had sat down"),
     QString("sat I down")},
    {QString("leave"), QString("leaving"), QString("left"), QString("to leave")},
    {QString("leave"), QString("leaving"), QString("left"), QString("to leave")},
    {QString("he did speak"), QString("spoke he"), QString("he spoke"), QString("did he speak")},
    {QString("learned"), QString("learn"), QString("had learned"), QString("would learn")},
    {QString("will have been completed"), QString("is completing"), QString("would complete"),
     QString("will complete")},
  }};

inline const std::vector<std::vector<int>> grammar_answers = {
  {1, 1, 3, 3, 2, 2, 0, 2, 3, 2, 1, 3, 0, 3, 1, 1, 1, 0, 3, 1, 0, 2, 0, 1, 1, 2, 1, 2, 0, 2},
  {2, 0, 1, 2, 1, 3, 2, 0, 1, 2, 1, 3, 3, 0, 3, 3, 0, 3, 3, 0, 2, 1, 1, 3, 0, 1, 3, 1, 0, 0},
  {0, 1, 0, 3, 2, 0, 1, 1, 1, 2, 0, 3, 1, 3, 3, 2, 3, 3, 1, 3, 3, 3, 1, 0, 1, 1, 1, 3, 2, 0}};

inline const std::vector<std::vector<QString>> translation_questions = {
  {
    QString("cat"),      QString("dog"),    QString("house"),  QString("car"),
    QString("book"),     QString("table"),  QString("water"),  QString("tree"),
    QString("sun"),      QString("moon"),   QString("school"), QString("teacher"),
    QString("friend"),   QString("family"), QString("city"),   QString("country"),
    QString("street"),   QString("window"), QString("door"),   QString("chair"),
    QString("computer"), QString("phone"),  QString("food"),   QString("music"),
    QString("coffee"),   QString("tea"),    QString("apple"),  QString("banana"),
    QString("pen"),      QString("paper"),
  },
  {
    QString("I am hungry."),
    QString("She is reading a book."),
    QString("They go to school by bus."),
    QString("He likes to play football."),
    QString("We live in a big city."),
    QString("The cat is sleeping on the sofa."),
    QString("My brother is watching TV now."),
    QString("I have finished my homework."),
    QString("She was cooking dinner when I arrived."),
    QString("They will travel to Paris next year."),
    QString("The sun rises in the east."),
    QString("I don't understand this question."),
    QString("Can you help me, please?"),
    QString("He doesn't know the answer."),
    QString("We are going to the cinema tonight."),
    QString("Do you speak English?"),
    QString("She has been to London twice."),
    QString("I saw him yesterday."),
    QString("They had already left."),
    QString("The children are playing in the garden."),
    QString("I will call you tomorrow."),
    QString("He works as a doctor."),
    QString("We visited the museum last weekend."),
    QString("She loves listening to music."),
    QString("It is raining heavily."),
    QString("I want to learn English."),
    QString("They didn't come to the party."),
    QString("He bought a new car."),
    QString("She writes letters every day."),
    QString("We watched the match on TV."),
  },
  {
    QString("A picture is worth a thousand words."),
    QString("Actions speak louder than words."),
    QString("The early bird catches the worm."),
    QString("Don't count your chickens before they hatch."),
    QString("Every cloud has a silver lining."),
    QString("Too many cooks spoil the broth."),
    QString("Don't put all your eggs in one basket."),
    QString("When in Rome, do as the Romans do."),
    QString("The grass is always greener on the other side."),
    QString("Don't bite the hand that feeds you."),
    QString("A watched pot never boils."),
    QString("Beggars can't be choosers."),
    QString("Better late than never."),
    QString("Birds of a feather flock together."),
    QString("Cleanliness is next to godliness."),
    QString("Don't cry over spilt milk."),
    QString("Fortune favors the bold."),
    QString("Honesty is the best policy."),
    QString("If it ain't broke, don't fix it."),
    QString("Practice makes perfect."),
    QString("Two heads are better than one."),
    QString("Where there's smoke, there's fire."),
    QString("You can't judge a book by its cover."),
    QString("The pen is mightier than the sword."),
    QString("Necessity is the mother of invention."),
    QString("A rolling stone gathers no moss."),
    QString("Look before you leap."),
    QString("Too little, too late."),
    QString("Beauty is in the eye of the beholder."),
    QString("Absence makes the heart grow fonder."),
  }
};

inline const std::vector<std::vector<QString>> translations_answers = {
  {
    QString("кот"),       QString("собака"),  QString("дом"),    QString("машина"),
    QString("книга"),     QString("стол"),    QString("вода"),   QString("дерево"),
    QString("солнце"),    QString("луна"),    QString("школа"),  QString("учитель"),
    QString("друг"),      QString("семья"),   QString("город"),  QString("страна"),
    QString("улица"),     QString("окно"),    QString("дверь"),  QString("стул"),
    QString("компьютер"), QString("телефон"), QString("еда"),    QString("музыка"),
    QString("кофе"),      QString("чай"),     QString("яблоко"), QString("банан"),
    QString("ручка"),     QString("бумага"),
  },
  {
    QString("Я голоден."),
    QString("Она читает книгу."),
    QString("Они едут в школу на автобусе."),
    QString("Он любит играть в футбол."),
    QString("Мы живём в большом городе."),
    QString("Кошка спит на диване."),
    QString("Мой брат сейчас смотрит телевизор."),
    QString("Я закончил свою домашнюю работу."),
    QString("Она готовила ужин, когда я пришёл."),
    QString("Они поедут в Париж в следующем году."),
    QString("Солнце встаёт на востоке."),
    QString("Я не понимаю этот вопрос."),
    QString("Не могли бы вы мне помочь, пожалуйста?"),
    QString("Он не знает ответа."),
    QString("Мы собираемся в кино сегодня вечером."),
    QString("Ты говоришь по-английски?"),
    QString("Она была в Лондоне два раза."),
    QString("Я видел его вчера."),
    QString("Они уже ушли."),
    QString("Дети играют в саду."),
    QString("Я позвоню тебе завтра."),
    QString("Он работает врачом."),
    QString("Мы посетили музей в прошлые выходные."),
    QString("Она любит слушать музыку."),
    QString("Идёт сильный дождь."),
    QString("Я хочу выучить английский."),
    QString("Они не пришли на вечеринку."),
    QString("Он купил новую машину."),
    QString("Она пишет письма каждый день."),
    QString("Мы смотрели матч по телевизору."),
  },
  {
    QString("Картина стоит тысячи слов."),
    QString("Дела говорят громче слов."),
    QString("Кто рано встает, тому Бог подает."),
    QString("Не считай цыплят до того, как они вылупятся."),
    QString("Нет худа без добра."),
    QString("Слишком много поваров портят бульон."),
    QString("Не клади все яйца в одну корзину."),
    QString("Когда ты в Риме, веди себя как римляне."),
    QString("Трава всегда зеленее на другой стороне."),
    QString("Не кусай руку, которая тебя кормит."),
    QString("Наблюдаемая кастрюля никогда не кипит."),
    QString("Нищие не могут выбирать."),
    QString("Лучше поздно, чем никогда."),
    QString("Птицы одного полета держатся вместе."),
    QString("Чистота — залог благочестия."),
    QString("Не плачь над пролитым молоком."),
    QString("Удача любит смелых."),
    QString("Честность — лучшая политика."),
    QString("Если это не сломано, не чини."),
    QString("Практика доводит до совершенства."),
    QString("Две головы лучше одной."),
    QString("Где дым, там и огонь."),
    QString("Не суди книгу по обложке."),
    QString("Перо сильнее меча."),
    QString("Необходимость — мать изобретений."),
    QString("Катящийся камень мха не обрастает."),
    QString("Смотри, прежде чем прыгать."),
    QString("Слишком мало, слишком поздно."),
    QString("Красота в глазах смотрящего."),
    QString("Разлука укрепляет чувства."),
  }
};

inline std::unique_ptr<GrammarTask> GetGrammarTask(TaskDifficulty difficulty, const int& id) {
    const int difficulty_id = static_cast<int>(difficulty);
    return std::make_unique<GrammarTask>(
        std::make_unique<QString>(grammar_questions[difficulty_id][id]),
        std::make_unique<std::vector<QString>>(grammar_options[difficulty_id][id]),
        std::make_unique<int>(grammar_answers[difficulty_id][id]));
}

inline std::unique_ptr<TranslationTask> GetTranslationTask(
    TaskDifficulty difficulty, const int& id) {
    const int difficulty_id = static_cast<int>(difficulty);
    return std::make_unique<TranslationTask>(
        std::make_unique<QString>(translation_questions[difficulty_id][id]),
        std::make_unique<QString>(translations_answers[difficulty_id][id]));
}

}  // namespace DataBase

#endif  // DATABASE_H
